install(
	TARGETS ${PROJECT_NAME}
	RUNTIME DESTINATION bin
	LIBRARY DESTINATION lib
	ARCHIVE DESTINATION lib
)

install(
	DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/minter
	DESTINATION include/
)

if (ENABLE_CONAN)
	install(DIRECTORY ${CONAN_INCLUDE_DIRS_BIP39}/bip3x/
	        DESTINATION ${CMAKE_INSTALL_PREFIX}/include/bip3x/
	        )

	install(DIRECTORY ${CONAN_INCLUDE_DIRS_TOOLBOX}/toolbox/
	        DESTINATION ${CMAKE_INSTALL_PREFIX}/include/toolbox/
	        )
endif ()