version: 2.1
commands:
  init:
    steps:
      - run: sudo apt-get update

  checkout_recursive:
    steps:
      - run:
          name: Checkout
          command: git clone --recursive https://github.com/MinterTeam/cpp-minter .
  conan_remotes:
    steps:
      - run: conan remote add -f edwardstock https://edwardstock.jfrog.io/artifactory/api/conan/conan
      - run: conan remote add -f minter https://minter.jfrog.io/artifactory/api/conan/conan
      - run: conan user -p $ARTIFACTORY_API_KEY -r minter edward.vstock@gmail.com

  conan_project_deps:
    steps:
      - run:
          name: Project dependencies
          command: $(which bash) .circleci/conan_deps.sh

  test:
    steps:
      - run:
          name: Testing
          command: $(which bash) .circleci/test.sh

  deploy_conan:
    steps:
      - run:
          name: Deploy to Conan bintray
          command: $(which bash) .circleci/deploy.sh

  do_all_centos:
    steps:
      - checkout_recursive
      - conan_remotes
      - conan_project_deps
      - test
      - deploy_conan

  do_all:
    steps:
      - init
      - checkout_recursive
      - conan_remotes
      - conan_project_deps
      - test
      - deploy_conan

jobs:
  gcc-5:
    docker:
      - image: conanio/gcc5
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-6:
    docker:
      - image: conanio/gcc6
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-7:
    docker:
      - image: conanio/gcc7
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-8:
    docker:
      - image: conanio/gcc8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-9:
    docker:
      - image: conanio/gcc9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-10:
    docker:
      - image: conanio/gcc10
        auth:
          username: $DOCKER_USER
          password: $DOCKER_TOKEN
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all

workflows:
  build_and_test:
    jobs:
      - gcc-5:
          context:
            - remote_tokens
      - gcc-6:
          context:
            - remote_tokens
      - gcc-7:
          context:
            - remote_tokens
      - gcc-8:
          context:
            - remote_tokens
      - gcc-9:
          context:
            - remote_tokens
      - gcc-10:
          context:
            - remote_tokens
#      - package_all:
#          context:
#            - remote_tokens